In [1]:
import pandas as pd
import pickle

In [2]:
# Load the unseen data
ds = pd.read_csv('RealEstatePrediction.csv')
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   X2 house age                            22 non-null     float64
 1   X3 distance to the nearest MRT station  22 non-null     float64
 2   X4 number of convenience stores         22 non-null     int64
 3   X5 latitude                             22 non-null     float64
 4   X6 longitude                            22 non-null     float64
dtypes: float64(4), int64(1)
memory usage: 1012.0 bytes

In [3]:
# Open the pickle file for reading in binary mode
with open("regmodel.pkl", "rb") as file:
    # Load the contents of the pickle file
    model = pickle.load(file)

In [4]:
X = ds.copy(deep=True)
print(X.columns)

Index(['X2 house age', 'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude'],
      dtype='object')

In [5]:
# Run the prediction
y_pred= model.predict(X)

In [6]:
# Add a new column "Predicted" to the original DataFrame X
X['Predicted'] = y_pred
X

,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Predicted
0,32.0,84.87882,10,24.98298,121.54024,46.643325
1,19.5,306.59470,9,24.98034,121.53951,46.825152
2,13.3,561.98450,5,24.98746,121.54391,43.035784
3,13.3,561.98450,5,24.98746,121.54391,43.035784
4,5.0,390.56840,5,24.97937,121.54245,49.872679
5,7.1,2175.03000,3,24.96305,121.51254,27.097817
6,34.5,623.47310,7,24.97933,121.53642,39.791189
7,20.3,287.60250,6,24.98042,121.54228,47.690111
8,31.7,5512.03800,1,24.95095,121.48458,17.533970
9,17.9,1783.18000,3,24.96731,121.51486,27.833068
10,34.8,405.21340,1,24.97349,121.53372,39.397549
11,6.3,90.45606,9,24.97433,121.54310,52.972860
12,13.0,492.23130,5,24.96515,121.53737,40.551398
13,20.4,2469.64500,4,24.96108,121.51046,27.622704
14,13.2,1164.83800,4,24.99156,121.53406,35.640826
15,35.7,579.20830,2,24.98240,121.54619,41.358231
16,0.0,292.99780,6,24.97744,121.54458,54.118031
17,17.7,350.85150,1,24.97544,121.53119,41.582524
18,16.9,368.13630,8,24.96750,121.54451,43.815044
19,1.5,23.38284,7,24.96772,121.54102,50.223938
20,4.5,2275.87700,3,24.96314,121.51151,27.466281
21,10.5,279.17260,7,24.97528,121.54541,52.067378